name: Deploy project
on: [push, workflow_dispatch]
jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setuo-node@v4
        with:
          node-version: 18
      - name: Install dependecies
        run: npm install
      - name: run test
        run: npm test
    
    
        
