name: context testing
on: push
jobs:
  dump_context_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
      id: github_context_step
      run: echo '${{toJson(github)}}'
      - name: Dump Job context
      run: echo '${{toJson(job)}}'
      - name: Dump Job context
      run: echo '${{toJson(steps)}}'
      - name: Dump runner context
      run: echo '${{toJson(runner)}}'
      - name: Dump to stretgy context
      run: echo '${{toJson(strategy)}}'
      - name: Dump matrix context
      run: echo '${{toJson(matrix)}}'
      
