name: first-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello pape"
      - name: print goodbye
        run: echo "Done|| -bye"

  secound-job:
    runs-on: ubuntu-latest
    steps:
      - name: bla bla
        run: echo "bla-bla"
